package main

import (
	"LogGenerator/filter"
	"LogGenerator/segment"
	"flag"
	"fmt"
	"log/slog"

	"time"
)

func main() {
	filePath := flag.String("in", "/home/kiruthika/LogGenerator/logs", "Input TSON file generated by log_parser (required)")
	level := flag.String("level", "", "Filter by log level")
	component := flag.String("component", "", "Filter by component")
	host := flag.String("host", "", "Filter by host")
	reqID := flag.String("reqID", "", "Filter by requestID")
	startTimeStr := flag.String("start", "", "Filter logs from this start time (YYYY-MM-DD HH:MM:SS)")
	endTimestr := flag.String("end", "", "Filter logs up to this end time (YYYY-MM-DD HH:MM:SS)")
	flag.Parse()
	var startTime, endTime time.Time
	var err error
	startTime = parseTimeFlag(*startTimeStr)
	endTime = parseTimeFlag(*endTimestr)
	logStore, err := segment.ParseLogSegments(*filePath)
	if err != nil {
		slog.Error("Failed to parse logs\n")
	}
	levels := split(*level)
	components := split(*component)
	hosts := split(*host)
	reqIDs := split(*reqID)
	filteredLogs := filter.FilterLogs(logStore, levels, components, hosts, reqIDs, startTime, endTime)
	fmt.Printf("Found %d matching entries\n", len(filteredLogs))
	for _, entry := range filteredLogs {
		fmt.Println(entry.Raw)
	}
}
